#!/usr/bin/env bash

set -CEeuo pipefail
IFS=$'\n\t'
shopt -s extdebug

load_commonsh

main() {
  header "Pulling latest version of provision repo"
  (
  cd $PROVISION_DIR
  git pull
  )
}

main "$@"
