#!/usr/bin/env bash

set -CEeuo pipefail
IFS=$'\n\t'
shopt -s extdebug

load_commonsh

main() {
  if [[ $* == *--no-fetch* ]]; then
    header "Skipping remote pull (--no-fetch)"
  else
    provision update
  fi
  header "Getting files from repo and placing onto system."
  local item_name
  local system_path
  local repo_path
  let FINAL_INDEX=$FILES_COUNT-1
  for i in $(seq 0 $FINAL_INDEX); do
    if [[ $(there_is_system_configuration_for_index $i) == 'true' ]]; then
      item_name=$(item_name_for_index $i)
      system_path=$(system_path_for_index $i)
      repo_path=$(repo_path_for_index $i)
      replace_on_system $item_name $system_path $repo_path
    fi
  done
  header "Done! Your provision are updated!"
}

main "$@"
