#!/usr/bin/env bash

set -CEeuo pipefail
IFS=$'\n\t'
shopt -s extdebug

resolve_link() {
  $(type -p greadlink readlink | head -1) "$1"
}

abs_dirname() {
  local cwd
  cwd="$(pwd)"
  local path="$1"

  while [ -n "$path" ]; do
    cd "${path%/*}"
    local name="${path##*/}"
    path="$(resolve_link "$name" || true)"
  done

  pwd
  cd "$cwd"
}

libexec_path="$(abs_dirname "$0")"
_PROVISION_ROOT="$(abs_dirname "$libexec_path")"
export _PROVISION_ROOT
export PROVISION_DIR="$_PROVISION_ROOT"

load_commonsh() {
  # shellcheck disable=SC1090
  source "$PROVISION_DIR/libexec/lib/common.sh"
}

export -f load_commonsh

load_commonsh

export PATH="${libexec_path}:$PATH"

export SYSTEM

if [[ $(uname) == 'Linux' ]]; then
  SYSTEM='linux'
else
  SYSTEM='mac'
fi

command="${1:-""}"
case "$command" in
  "" | "-h" | "--help")
    exec provision-help
    ;;
  *)
    command_path="$(command -v "provision-$command" || true)"
    if [ ! -x "$command_path" ]; then
      echo "provision: no such command \`$command'" >&2
      exit 1
    fi

    shift
    exec "$command_path" "$@"
    ;;
esac
