#!/usr/bin/env bash

load_commonsh

do_run() {
    local action
    local package_name
    local script_path
    local result_code
    ensure_args "2" "$#"
    action="$1"
    package_name="$2"
    script_path=$(package_script "$package_name")
    set +e
    (
        eval "$(cat $script_path)"
        eval "$action"
    )
    result_code="$?"
    set -e
    if [ "$result_code" -eq "1" ]; then
        echo "Failed to $action $package_name."
      if "${HARD_FAIL:-true}" eq "true"; then
          echo "HARD_FAIL=true, so aborting"
          exit 1
      fi
    fi
}

main() {
    local action
    local package_name
    local script_path
    ensure_args "2" "$#"
    action="$1"
    package_name="$2"
    if [ "$package_name" == "--all" ]; then
        for file in $PACKAGES_DIR/*; do
            package_name=$(basename "$file")
            do_run "$action" "$package_name"
        done
    else
        do_run "$action" "$package_name"
    fi
}

main "$@"
