#!/usr/bin/env bash

load_commonsh

main() {
  local package_name
  ensure_args "1" "$#"
  package_name="$1"
  if [ "$package_name" == "--all" ]; then
    for file in $PACKAGES_DIR/*; do
      package_name=$(basename "$file")
      provision install "$package_name"
    done
  else
    if (run_package_command "$package_name" "verify"); then

      echo "$(padded_package_name "$package_name")already installed"
      exit 0
    else
      error "$package_name is not installed"
      if (run_package_command "$package_name" "install"); then
        echo "$(padded_package_name "$package_name")was successfully installed"
      else
        echo "$(padded_package_name "$package_name")failed to install"
      fi
    fi
  fi
}

main "$@"
